# Generated by Django 4.1.5 on 2023-05-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_liquor_detail_alter_liquor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='create',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='proof',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='base',
            field=models.CharField(choices=[('Whisky', '위스키'), ('Bodka', '보드카'), ('Gin', '진'), ('Rum', '럼'), ('Tequila', '데킬라')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='detail',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='proof',
            field=models.IntegerField(),
        ),
    ]
